### PR TITLE
Show passed in values

### PR DESCRIPTION
**Pull request by aconrad**
Addresses https://github.com/mikejsdev/mocha-param/issues/2.

### CODE REVIEW

**Comment by mhxbe** [comment]
Keep in mind that template literals won't work on node `0.12.x` & `0.10.x`.
Source: [http://node.green/#ES2015-syntax-template-literals](url)

To @mikejsdev: If this PR gets merged and published on npm, make sure to do a major bump since this will break on projects where the node version is still `0.12.x` or `0.10.x`.

What do you think?

**Comment by aconrad** [comment]
Valid concern, thanks for pointing this out @mhxbe! I still hope that this PR makes it in. I'd like to advocate for parametrized tests within my eng team and this library seems to get the job done nicely. Thanks for writing it @mikejsdev!

**Comment by mikejsdev** [comment]
@aconrad this is a really great solution to the problem, I was planning on sorting this out myself soon but I think your solution is spot on. I'm going to run some more tests and then merge your pull request.  Thanks for doing this.

@mhxbe I completely agree, really great point. I will merge and then republish to npm but I will make sure there is a version bump.

**Comment by aconrad** [comment]
@mikejsdev, can you please ping this thread when you publish a new release?

**Comment by mikejsdev** [comment]
Hi everyone, version 2.0.0 is now released.

Thanks again @aconrad for your help, please let me know if you have any issues.

**Comment by aconrad** [comment]
Awesome, thanks @mikejsdev! I suggest you also update the README info at https://www.npmjs.com/package/mocha-param so it illustrates how to do inject the test values in the description using `${value}`.

**Comment by aconrad** [comment]
Please ignore my comment above! I realize you have already done so, I had to scroll further down since I was just looking at "Basic Usage". 👍 Thanks again!

**Pull request merged**
